# Generated by Django 5.1.3 on 2024-12-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='size',
            name='code',
            field=models.CharField(default='', max_length=5),
        ),
    ]
